trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - script: |
      rm -rf node_modules
      npm ci
      npx playwright install --with-deps
    displayName: 'Install dependencies and Playwright'

  - script: npm run test
    displayName: 'Run Playwright Tests'

  - script: npx allure generate allure-results --clean -o allure-report
    displayName: 'Generate Allure Report'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'allure-report'
      artifact: 'allure-report'
